version: '3.8'

services:
  web:
    build: .
    ports:
      - "4000:3000"  # Map host port 4000 to container port 3000
    environment:
      - PERMIT_API_KEY=your_permit_api_key
      - PORT=3000
    volumes:
      - .:/app
